apiVersion: apps/v1
kind: Deployment
metadata: 
  name: web-api
spec:
  selector:
    matchLabels:
      app: web-api
  template:
    metadata:
      labels:
        app: web-api
    spec:
      containers:
        - name: web-api-container
          image: andriideveloper/dbis-web-api
          imagePullPolicy: Always
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: web-api
spec:
  selector:
    app: web-api
  ports:
    - name      : web-api-listener
      protocol  : TCP
      port      : 80
      targetPort: 80
  type: LoadBalancer
