# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.4'

services:
  educationonlineplatform:
    image: educationonlineplatform
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8000:80"

  pg:
    image: postgres:9.6-alpine
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    ports:
      - "3000:5432"
